workflows:
  my-ledger-android:
    name: My Ledger Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 21
    scripts:
      - name: Give Gradle permission
        script: chmod +x ./gradlew
      - name: Remove duplicate launcher resources
        script: |
          find app/src/main/res -type f \( -name "ic_launcher.webp" -o -name "ic_launcher_round.webp" \) -delete
      - name: Clean project
        script: ./gradlew clean --no-daemon
      - name: Build signed release APK
        script: ./gradlew :app:assembleRelease --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
